runtime: python312
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  script: auto

env_variables:
  CLIENT_ID: ${_CLIENT_ID}
  CLIENT_SECRET: ${_CLIENT_SECRET}
  #REDIRECT_URI: 'http://localhost:8080/callback'
  REDIRECT_URI: ${_REDIRECT_URI}
  SCOPE: ${_SCOPE}
