logsBucket: "gs://spotify-project-logs-bucket"
# steps:
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]
# timeout: "1600s"
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  env:
    - 'CLIENT_ID=$CLIENT_ID'
    - 'CLIENT_SECRET=$CLIENT_SECRET'
    - 'REDIRECT_URI=$REDIRECT_URI'
    - 'SCOPE=$SCOPE'
timeout: '1600s'

