logsBucket: "gs://spotify-project-logs-bucket"
steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://spotify-project-logs-bucket/spotify-env/env_variables.yaml', 'env_variables.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
    - gcloud
    - functions
    - deploy
    -  get-monthly-spotify-data
    - --entry-point=main
    - --region=us-central1
    - --source=./gcloud/gcloud_functions
    - --trigger-http
    - --runtime=python312
timeout: '1600s'

