main:
  steps:
  - invoke_spotify_app:
    call: http.post
    args:
      url: "https://deft-melody-404117.uc.r.appspot.com/get-data"
      body:
        ${data}
      headers:
        Content-Type: application/json
      result: flask_response
  # - call_get_spotify_monthly_data_from_bucket:
  #   call: http.get
  #   args:
  #     url: "https://europe-central2-deft-melody-404117.cloudfunctions.net/function-get_spotify_monthly_data_from_bucket"
  # - publish_to_pubsub:
  # - return_results: