fields:
  - name: "artist"
    type: "STRING"
  - name: "artist_link"
    type: "STRING"
  - name: "track_title"
    type: "STRING"
  - name: "track_link"
    type: "STRING"
  - name: "album"
    type: "STRING"
  - name: "album_type"
    type: "STRING"
  - name: "release_date"
    type: "STRING"
  - name: "popularity"
    type: "INTEGER"
  - name: "ranking_date"
    type: "DATE"